state_fix_map={
    'jammu and kashmir':'jammu kashmir',
'orissa':'odisha',
'the dadra and nagar haveli and daman and diu':'dadra and nagar haveli and daman and diu',
'dadra nagar haveli':'dadra and nagar haveli and daman and diu',
'dadra and nagar haveli':'dadra and nagar haveli and daman and diu',
'daman and diu':'dadra and nagar haveli and daman and diu',
'daman diu':'dadra and nagar haveli and daman and diu',
'andaman and nicobar islands':'andaman nicobar islands',
'west bangal':'west bengal',
'westbengal':'west bengal',
'puducherry':'pondicherry',
'chhatisgarh':'chhattisgarh',
'uttaranchal':'uttarakhand',
'west bengli':'west bengal',
'tamilnadu':'tamil nadu',

'100000': None
}
district_fix_map = {
    'allahabad':'prayagraj',
    'ahmadabad': 'ahmedabad',
    'ahmadnagar': 'ahilyanagar',
    'ahmed nagar': 'ahilyanagar',
    'ahmednagar':'ahilyanagar',
    'ananthapuramu': 'anantapuramu',
    'tiruvallur': 'thiruvallur',
    'anantapur': 'anantapuramu',
    'ananthapur':'anantapuramu',
    'ashok nagar': 'ashoknagar',
    'anugul': 'angul',
    'anugal': 'angul',
    'banas kantha': 'banaskantha',
    'bid':'beed',
    'bellary':'ballari',
    'belgaum':'belagavi',
    'bulandshahar': 'bulandshahr',
    'barddhaman': 'bardhaman',
    'baleshwar': 'baleswar',
    'barabanki': 'bara banki',
    'baudh': 'boudh',
    'bandipore': 'bandipora',
    'bandipur': 'bandipora',
    'buldana': 'buldhana',
    'baghpat': 'bagpat',
    'bangalore': 'bengaluru',
    'bangalore rural': 'bengaluru rural',
    'chamrajanagar': 'chamarajanagar',
    'chamrajnagar': 'chamarajanagar',
    'chickmagalur': 'chikkamagaluru',
    'chikmagalur': 'chikkamagaluru',
    'chhatrapati sambhajinagar': 'chatrapati sambhaji nagar',
    'coochbehar': 'cooch behar',
    'koch bihar': 'cooch behar',
    'chittaurgarh': 'chittorgarh',
    'cuddapah':'y s r kadapa',
    'dakshin bastar dantewada': 'dantewada',
    'davangere': 'davanagere',
    'dadra nagar haveli': 'dadra and nagar haveli',
    'dinajpur dakshin': 'dakshin dinajpur',
    'dhaulpur': 'dholpur',
    'darjiling': 'darjeeling',
    'east singhbum': 'east singhbhum',
    'east midnapur': 'purba medinipur',
    'east': 'east sikkim',
    'faizabad':'ayodhya',
    'ferozepur': 'firozpur',
    'gaurella pendra marwahi': 'gaurela penda marwahi',
    'gaurela pendra marwahi': 'gaurela penda marwahi',
    'gurgaon': 'gurugram',
    'gondiya': 'gondia',
    'garhwal': 'pauri garhwal',
    'hasan': 'hassan',
    'hugli': 'hooghly',
    'hooghiy': 'hooghly',
    'haora': 'howrah',
    'hardwar': 'haridwar',
    'hawrah': 'howrah',
    'hazaribag': 'hazaribagh',
    'hoshangabad':'narmadapuram',
    'jagatsinghapur': 'jagatsinghpur',
    'jajapur': 'jajpur',
    'jhunjhunun': 'jhunjhunu',
    'jalor': 'jalore',
    'jangoan': 'jangaon',
    'kasargod': 'kasaragod',
    'ranga reddy': 'rangareddy',
    'kv rangareddy':'rangareddy',
    'k.v. rangareddy': 'rangareddy',
    'k.v.rangareddy': 'rangareddy',
    'rangareddi': 'rangareddy',
    'karim nagar': 'karimnagar',
    'kushi nagar': 'kushinagar',
    'kancheepuram': 'kanchipuram',
    'khorda': 'khordha',
    'kodarma': 'koderma',
    'east nimar':'khandwa',
    'west nimar':'khargone',
    'kawardha':'kabeerdham',
    'lahul spiti': 'lahaul and spiti',
    'lahul and spiti': 'lahaul and spiti',
    'mahbubnagar': 'mahabubnagar',
    'mahbub nagar': 'mahabubnagar',
    'mahabub nagar': 'mahabubnagar',
    'medinipur west': 'paschim medinipur',
    'mohalla manpur ambagarh chowki': 'mohla manpur ambagarh chowki',
    'mohla manpur ambagarh chouki': 'mohla manpur ambagarh chowki',
    'mammit': 'mamit',
    'malda': 'maldah',
    'monghyr':'munger',
    'mysore': 'mysuru',
    'mewat':'nuh',
    'narsimhapur': 'narmadapuram',
    'nicobars': 'nicobar',
    'nabarangapur': 'nabarangpur',
    'nellore': 'sri potti sriramulu nellore',
    'north': 'north sikkim',
    'osmanabad':'dharashiv',
    'panch mahals':'panchmahals',
    'purbi champaran':'east champaran',
    'purba champaran':'east champaran', 
    'pashchim champaran':'west champaran',
    'palamau': 'palamu',
    'purnia': 'purnea',
    'puruliya': 'purulia',
    'pondicherry': 'puducherry',
    'rajauri': 'rajouri',
    'raebareli': 'rae bareli',
    'ramanagara': 'ramanagar',
    'sheikpura': 'sheikhpura',
    'sahebganj': 'sahibganj',
    'shimoga': 'shivamogga',
    'tumkur': 'tumakuru',
    'sundergarh': 'sundargarh',
    'viluppuram': 'villupuram',
    'west midnapore': 'paschim medinipur',
    '24 paraganas north': 'north 24 parganas',
    'north twenty four parganas': 'north 24 parganas',
    'south twenty four parganas': 'south 24 parganas',
    'south 24 pargana': 'south 24 parganas',
    'sant ravidas nagar': 'sant ravidas nagar bhadohi',
    '24 paraganas south': 'south 24 parganas',
    'tiruvarur': 'thiruvarur',
    'visakhapatanam': 'visakhapatnam',
    'burdwan': 'bardhaman',
    'tuticorin': 'thoothukkudi',
    's.a.s nagar': 'sas nagar',
    'shrawasti': 'shravasti',
    'siddharth nagar': 'siddharthnagar',
    'yamuna nagar': 'yamunanagar',
    'yadadri.': 'yadadri bhuvanagiri',
    'sabar kantha': 'sabarkantha',
    'surendra nagar': 'surendranagar',
    'y s r': 'y s r kadapa',
    'south': 'south sikkim',
    "bengaluru": "bengaluru urban",
    "bengaluru south": "bengaluru urban",
    "mewat": "nuh",
    "spsr nellore": "nellore",
    "sri potti sriramulu nellore": "nellore",
    "sibsagar": "sivasagar",
    "samstipur": "samastipur",
    "shupiyan": "shopian",
    "dohad": "dahod",
    "dinajpur uttar": "north dinajpur",
    "north cachar hills": "dima hasao",
    "gulbarga": "kalaburagi",
    "baleswar": "balasore",
    "sri potti sriramulu nellore": "nellore",
    "jyotiba phule nagar": "amroha",
    "dr b r ambedkar konaseema": "konaseema",
    "k v rangareddy": "rangareddy",
    "y s r kadapa": "kadapa",
    "dist : thane": "thane",
    "tamulpur district": "tamulpur",
    "the dangs": "dang",
    "the nilgiris": "nilgiris",
    "balianta": "khordha",
    "bally jagachha": "howrah",
    "domjur": "howrah",
    "south dumdum": "north 24 parganas",
    "naihati anandabazar": "north 24 parganas",
    'bicholim':'north goa',
    'mohali':'s a s nagar',
    'kanyakumari': 'kanniyakumari',
    'west':'west sikkim',
    'manendragarhchirmiribharatpur':'manendragarh chirmiri bharatpur',

}

andhra_pradesh_to_telangana = [
    {
    "districts": [
        'adilabad','hyderabad','karimnagar','khammam','medak',
        'nalgonda','nizamabad','rangareddy','warangal','mahabubnagar'
    ],
    "from_state": "andhra pradesh",
    "to_state": "telangana",
    }
]

jammu_kashmir_to_ladakh = [
    {
    "districts": ['kargil', 'leh'],
    "from_state": "jammu kashmir",
    "to_state": "ladakh",
    }
]

state_district_rules= [
    {
        "match_state": "raja annamalai puram",
        "new_state": "tamil nadu",
        "new_district": "chennai",
    },
    {
        "match_state": "puttenahalli",
        "new_state": "karnataka",
        "new_district": "bengaluru urban",
    },
    {
        "match_state": "nagpur",
        "new_state": "maharashtra",
        "new_district": "nagpur",
    },
    {
        "match_state": "madanapalle",
        "new_state": "andhra pradesh",
        "new_district": "annamayya",
    },
    {
        "match_state": "jaipur",
        "new_state": "rajasthan",
        "new_district": "jaipur",
    },
    {
        "match_state": "balanagar",
        "new_state": "telangana",
        "new_district": "medchal malkajgiri",
    },
    {
        "match_state": "darbhanga",
        "new_state": "bihar",
        "new_district": "darbhanga",
    },
    {
        "match_state": "jammu kashmir",
        "match_district": "",
        "new_district": "jammu",
    },
]

rename_column = {
    'age_0_5': 'enrol_age_0_5',
    'age_5_17': 'enrol_age_5_17',
    'age_18_greater': 'enrol_age_18+',
    'demo_age_17_':'demo_age_17+',
    'bio_age_17_':'bio_age_17+'
}
keys = ['date', 'state', 'district', 'pincode']

counts = [
    'enrol_age_0_5',
    'enrol_age_5_17',
    'enrol_age_18+',
    'demo_age_5_17',
    'demo_age_17+',
    'bio_age_5_17',
    'bio_age_17+',
]